local:
- path: recipes/boltons/recipe.yaml
# - path: recipes/pthread-stubs/recipe.yaml
# - path: recipes/zlib/recipe.yaml
rattler-build:
  rev: 6f2c48e6e490967f3c47253c092853ee8fce9d57
  url: https://github.com/prefix-dev/rattler-build.git
# repositories:
# - branch: main
#   recipes:
#   - path: examples/rich/recipe.yaml
#   - path: examples/curl/recipe.yaml
#   url: https://github.com/prefix-dev/rattler-build.git
