local:
- path: recipes/boltons/recipe.yaml
- path: recipes/fastapi/recipe.yaml
- path: recipes/ca-certificates/recipe.yaml
- path: recipes/conda/recipe.yaml
- path: recipes/setuptools/recipe.yaml
- path: recipes/zlib/recipe.yaml
- path: recipes/pip/recipe.yaml
- path: recipes/wheel/recipe.yaml
- path: recipes/pytz/recipe.yaml
- path: recipes/six/recipe.yaml
- path: recipes/python-dateutil/recipe.yaml
- path: recipes/libpng/recipe.yaml
- path: recipes/jpeg/recipe.yaml
- path: recipes/freetype/recipe.yaml
- path: recipes/xz/recipe.yaml
- path: recipes/_openmp_mutex/recipe.yaml
- path: recipes/libffi/recipe.yaml
- path: recipes/_libgcc_mutex/recipe.yaml
- path: recipes/pthread-stubs/recipe.yaml
- path: recipes/lerc/recipe.yaml
- path: recipes/libnsl/recipe.yaml
- path: recipes/pcre2/recipe.yaml
- path: recipes/tomli/recipe.yaml
- path: recipes/brotli/recipe.yaml
- path: recipes/pyparsing/recipe.yaml
- path: recipes/pixman/recipe.yaml
- path: recipes/kiwisolver/recipe.yaml
- path: recipes/fonts-conda-forge/recipe.yaml
- path: recipes/fonts-conda-ecosystem/recipe.yaml
- path: recipes/cycler/recipe.yaml
- path: recipes/font-ttf-source-code-pro/recipe.yaml
- path: recipes/font-ttf-inconsolata/recipe.yaml
- path: recipes/font-ttf-dejavu-sans-mono/recipe.yaml
- path: recipes/font-ttf-ubuntu/recipe.yaml
- path: recipes/xorg-kbproto/recipe.yaml
- path: recipes/munkres/recipe.yaml
- path: recipes/xorg-xproto/recipe.yaml
- path: recipes/toml/recipe.yaml
- path: recipes/sqlite/recipe.yaml
rattler-build:
  branch: fix/conda-timestamp-affect-reproducibility
  url: https://github.com/nichmor/rattler-build.git
repositories:
- branch: rattler-build
  recipes:
  - path: recipe/recipe.yaml
  url: https://github.com/conda-forge/polarify-feedstock.git
- branch: main
  recipes:
  - path: examples/xtensor/recipe.yaml
  - path: examples/ros-humble-turtlebot4-msgs/recipe.yaml
  - path: examples/rich/recipe.yaml
  - path: examples/mamba/recipe.yaml
  - path: examples/linking/recipe.yaml
  - path: examples/curl/recipe.yaml
  - path: examples/cmpcdt/recipe.yaml
  - path: examples/cargo-edit/recipe.yaml
  url: https://github.com/prefix-dev/rattler-build.git
